#to check alert making outofsync
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-webapp
  namespace: portfolio
  labels:
    app: portfolio-webapp
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-webapp
  template:
    metadata:
      labels:
        app: portfolio-webapp
    spec:
      containers:
        - name: portfolio-webapp
          image: vigneshlucky000/webapp:build-23
          imagePullPolicy: Always
          ports:
            - containerPort: 80
