apiVersion: v1
kind: Service
metadata:
  name: portfolio-webapp-service
  namespace: portfolio
spec:
  type: LoadBalancer
  selector:
    app: portfolio-webapp
  ports:
    - port: 80
      targetPort: 80
